// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package repository -source=contract.go -destination=mock_repository.go *
//

// Package repository is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/cchristian77/wallet-service/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockRepository) CreateTransaction(ctx context.Context, data *domain.Transaction) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, data)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockRepositoryMockRecorder) CreateTransaction(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockRepository)(nil).CreateTransaction), ctx, data)
}

// CreateTransactionLedger mocks base method.
func (m *MockRepository) CreateTransactionLedger(ctx context.Context, data *domain.TransactionLedger) (*domain.TransactionLedger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionLedger", ctx, data)
	ret0, _ := ret[0].(*domain.TransactionLedger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransactionLedger indicates an expected call of CreateTransactionLedger.
func (mr *MockRepositoryMockRecorder) CreateTransactionLedger(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionLedger", reflect.TypeOf((*MockRepository)(nil).CreateTransactionLedger), ctx, data)
}

// FindTransactionByTransactionID mocks base method.
func (m *MockRepository) FindTransactionByTransactionID(ctx context.Context, transactionID string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransactionByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTransactionByTransactionID indicates an expected call of FindTransactionByTransactionID.
func (mr *MockRepositoryMockRecorder) FindTransactionByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionByTransactionID", reflect.TypeOf((*MockRepository)(nil).FindTransactionByTransactionID), ctx, transactionID)
}

// FindTransactionLedgersByTransactionID mocks base method.
func (m *MockRepository) FindTransactionLedgersByTransactionID(ctx context.Context, transactionID uint64) ([]*domain.TransactionLedger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransactionLedgersByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].([]*domain.TransactionLedger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTransactionLedgersByTransactionID indicates an expected call of FindTransactionLedgersByTransactionID.
func (mr *MockRepositoryMockRecorder) FindTransactionLedgersByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionLedgersByTransactionID", reflect.TypeOf((*MockRepository)(nil).FindTransactionLedgersByTransactionID), ctx, transactionID)
}

// FindWalletByID mocks base method.
func (m *MockRepository) FindWalletByID(ctx context.Context, id uint64) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWalletByID", ctx, id)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWalletByID indicates an expected call of FindWalletByID.
func (mr *MockRepositoryMockRecorder) FindWalletByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWalletByID", reflect.TypeOf((*MockRepository)(nil).FindWalletByID), ctx, id)
}

// FindWalletByIDForUpdate mocks base method.
func (m *MockRepository) FindWalletByIDForUpdate(ctx context.Context, id uint64) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWalletByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWalletByIDForUpdate indicates an expected call of FindWalletByIDForUpdate.
func (mr *MockRepositoryMockRecorder) FindWalletByIDForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWalletByIDForUpdate", reflect.TypeOf((*MockRepository)(nil).FindWalletByIDForUpdate), ctx, id)
}

// FindWalletByUserID mocks base method.
func (m *MockRepository) FindWalletByUserID(ctx context.Context, userID uint64) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWalletByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWalletByUserID indicates an expected call of FindWalletByUserID.
func (mr *MockRepositoryMockRecorder) FindWalletByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWalletByUserID", reflect.TypeOf((*MockRepository)(nil).FindWalletByUserID), ctx, userID)
}

// UpdateTransactionStatus mocks base method.
func (m *MockRepository) UpdateTransactionStatus(ctx context.Context, id uint64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionStatus indicates an expected call of UpdateTransactionStatus.
func (mr *MockRepositoryMockRecorder) UpdateTransactionStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockRepository)(nil).UpdateTransactionStatus), ctx, id, status)
}

// UpdateWalletBalance mocks base method.
func (m *MockRepository) UpdateWalletBalance(ctx context.Context, walletID uint64, balance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWalletBalance", ctx, walletID, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWalletBalance indicates an expected call of UpdateWalletBalance.
func (mr *MockRepositoryMockRecorder) UpdateWalletBalance(ctx, walletID, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWalletBalance", reflect.TypeOf((*MockRepository)(nil).UpdateWalletBalance), ctx, walletID, balance)
}

// MockWalletRepository is a mock of WalletRepository interface.
type MockWalletRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWalletRepositoryMockRecorder
	isgomock struct{}
}

// MockWalletRepositoryMockRecorder is the mock recorder for MockWalletRepository.
type MockWalletRepositoryMockRecorder struct {
	mock *MockWalletRepository
}

// NewMockWalletRepository creates a new mock instance.
func NewMockWalletRepository(ctrl *gomock.Controller) *MockWalletRepository {
	mock := &MockWalletRepository{ctrl: ctrl}
	mock.recorder = &MockWalletRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletRepository) EXPECT() *MockWalletRepositoryMockRecorder {
	return m.recorder
}

// FindWalletByID mocks base method.
func (m *MockWalletRepository) FindWalletByID(ctx context.Context, id uint64) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWalletByID", ctx, id)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWalletByID indicates an expected call of FindWalletByID.
func (mr *MockWalletRepositoryMockRecorder) FindWalletByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWalletByID", reflect.TypeOf((*MockWalletRepository)(nil).FindWalletByID), ctx, id)
}

// FindWalletByIDForUpdate mocks base method.
func (m *MockWalletRepository) FindWalletByIDForUpdate(ctx context.Context, id uint64) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWalletByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWalletByIDForUpdate indicates an expected call of FindWalletByIDForUpdate.
func (mr *MockWalletRepositoryMockRecorder) FindWalletByIDForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWalletByIDForUpdate", reflect.TypeOf((*MockWalletRepository)(nil).FindWalletByIDForUpdate), ctx, id)
}

// FindWalletByUserID mocks base method.
func (m *MockWalletRepository) FindWalletByUserID(ctx context.Context, userID uint64) (*domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWalletByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWalletByUserID indicates an expected call of FindWalletByUserID.
func (mr *MockWalletRepositoryMockRecorder) FindWalletByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWalletByUserID", reflect.TypeOf((*MockWalletRepository)(nil).FindWalletByUserID), ctx, userID)
}

// UpdateWalletBalance mocks base method.
func (m *MockWalletRepository) UpdateWalletBalance(ctx context.Context, walletID uint64, balance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWalletBalance", ctx, walletID, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWalletBalance indicates an expected call of UpdateWalletBalance.
func (mr *MockWalletRepositoryMockRecorder) UpdateWalletBalance(ctx, walletID, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWalletBalance", reflect.TypeOf((*MockWalletRepository)(nil).UpdateWalletBalance), ctx, walletID, balance)
}

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockTransactionRepository) CreateTransaction(ctx context.Context, data *domain.Transaction) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, data)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionRepositoryMockRecorder) CreateTransaction(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionRepository)(nil).CreateTransaction), ctx, data)
}

// FindTransactionByTransactionID mocks base method.
func (m *MockTransactionRepository) FindTransactionByTransactionID(ctx context.Context, transactionID string) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransactionByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTransactionByTransactionID indicates an expected call of FindTransactionByTransactionID.
func (mr *MockTransactionRepositoryMockRecorder) FindTransactionByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionByTransactionID", reflect.TypeOf((*MockTransactionRepository)(nil).FindTransactionByTransactionID), ctx, transactionID)
}

// UpdateTransactionStatus mocks base method.
func (m *MockTransactionRepository) UpdateTransactionStatus(ctx context.Context, id uint64, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionStatus indicates an expected call of UpdateTransactionStatus.
func (mr *MockTransactionRepositoryMockRecorder) UpdateTransactionStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateTransactionStatus), ctx, id, status)
}

// MockTransactionLedgerRepository is a mock of TransactionLedgerRepository interface.
type MockTransactionLedgerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionLedgerRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionLedgerRepositoryMockRecorder is the mock recorder for MockTransactionLedgerRepository.
type MockTransactionLedgerRepositoryMockRecorder struct {
	mock *MockTransactionLedgerRepository
}

// NewMockTransactionLedgerRepository creates a new mock instance.
func NewMockTransactionLedgerRepository(ctrl *gomock.Controller) *MockTransactionLedgerRepository {
	mock := &MockTransactionLedgerRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionLedgerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionLedgerRepository) EXPECT() *MockTransactionLedgerRepositoryMockRecorder {
	return m.recorder
}

// CreateTransactionLedger mocks base method.
func (m *MockTransactionLedgerRepository) CreateTransactionLedger(ctx context.Context, data *domain.TransactionLedger) (*domain.TransactionLedger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionLedger", ctx, data)
	ret0, _ := ret[0].(*domain.TransactionLedger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransactionLedger indicates an expected call of CreateTransactionLedger.
func (mr *MockTransactionLedgerRepositoryMockRecorder) CreateTransactionLedger(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionLedger", reflect.TypeOf((*MockTransactionLedgerRepository)(nil).CreateTransactionLedger), ctx, data)
}

// FindTransactionLedgersByTransactionID mocks base method.
func (m *MockTransactionLedgerRepository) FindTransactionLedgersByTransactionID(ctx context.Context, transactionID uint64) ([]*domain.TransactionLedger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransactionLedgersByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].([]*domain.TransactionLedger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTransactionLedgersByTransactionID indicates an expected call of FindTransactionLedgersByTransactionID.
func (mr *MockTransactionLedgerRepositoryMockRecorder) FindTransactionLedgersByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionLedgersByTransactionID", reflect.TypeOf((*MockTransactionLedgerRepository)(nil).FindTransactionLedgersByTransactionID), ctx, transactionID)
}
