--
-- PostgreSQL database dump
--

\restrict lmb2SFOZjv7JHAsg1uhif8va9KnhBxO8FfyAwGgBMlQM8u6N3FBfRGEDmfcyAE2

-- Dumped from database version 14.7 (Debian 14.7-1.pgdg110+1)
-- Dumped by pg_dump version 14.23

-- Started on 2026-07-26 07:22:38 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3384 (class 1262 OID 16539)
-- Name: wallet; Type: DATABASE; Schema: -; Owner: admin
--

CREATE DATABASE wallet WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE wallet OWNER TO admin;

\unrestrict lmb2SFOZjv7JHAsg1uhif8va9KnhBxO8FfyAwGgBMlQM8u6N3FBfRGEDmfcyAE2
\connect wallet
\restrict lmb2SFOZjv7JHAsg1uhif8va9KnhBxO8FfyAwGgBMlQM8u6N3FBfRGEDmfcyAE2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: admin
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO admin;

--
-- TOC entry 3385 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: admin
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 16541)
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO admin;

--
-- TOC entry 209 (class 1259 OID 16540)
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16593)
-- Name: transaction_ledgers; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.transaction_ledgers (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    transaction_id bigint NOT NULL,
    wallet_id bigint NOT NULL,
    ledger character varying(16) NOT NULL,
    reference character varying(32) NOT NULL,
    amount bigint NOT NULL,
    CONSTRAINT transaction_ledgers_amount_check CHECK ((amount > 0)),
    CONSTRAINT transaction_ledgers_ledger_check CHECK (((ledger)::text = ANY ((ARRAY['DEBIT'::character varying, 'CREDIT'::character varying])::text[]))),
    CONSTRAINT transaction_ledgers_reference_check CHECK (((reference)::text = ANY ((ARRAY['TOP_UP'::character varying, 'TRANSFER'::character varying, 'WITHDRAWAL'::character varying])::text[])))
);


ALTER TABLE public.transaction_ledgers OWNER TO admin;

--
-- TOC entry 217 (class 1259 OID 16592)
-- Name: transaction_ledgers_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.transaction_ledgers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.transaction_ledgers_id_seq OWNER TO admin;

--
-- TOC entry 3386 (class 0 OID 0)
-- Dependencies: 217
-- Name: transaction_ledgers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.transaction_ledgers_id_seq OWNED BY public.transaction_ledgers.id;


--
-- TOC entry 216 (class 1259 OID 16580)
-- Name: transactions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    transaction_id character varying(255),
    status character varying(16) NOT NULL,
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.transactions OWNER TO admin;

--
-- TOC entry 215 (class 1259 OID 16579)
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.transactions_id_seq OWNER TO admin;

--
-- TOC entry 3387 (class 0 OID 0)
-- Dependencies: 215
-- Name: transactions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.transactions_id_seq OWNED BY public.transactions.id;


--
-- TOC entry 212 (class 1259 OID 16548)
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    full_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password text NOT NULL
);


ALTER TABLE public.users OWNER TO admin;

--
-- TOC entry 211 (class 1259 OID 16547)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_id_seq OWNER TO admin;

--
-- TOC entry 3388 (class 0 OID 0)
-- Dependencies: 211
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 214 (class 1259 OID 16561)
-- Name: wallets; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.wallets (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    user_id bigint NOT NULL,
    balance bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.wallets OWNER TO admin;

--
-- TOC entry 213 (class 1259 OID 16560)
-- Name: wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.wallets_id_seq OWNER TO admin;

--
-- TOC entry 3389 (class 0 OID 0)
-- Dependencies: 213
-- Name: wallets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.wallets_id_seq OWNED BY public.wallets.id;


--
-- TOC entry 3199 (class 2604 OID 16596)
-- Name: transaction_ledgers id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transaction_ledgers ALTER COLUMN id SET DEFAULT nextval('public.transaction_ledgers_id_seq'::regclass);


--
-- TOC entry 3195 (class 2604 OID 16583)
-- Name: transactions id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transactions ALTER COLUMN id SET DEFAULT nextval('public.transactions_id_seq'::regclass);


--
-- TOC entry 3188 (class 2604 OID 16551)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 3191 (class 2604 OID 16564)
-- Name: wallets id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallets ALTER COLUMN id SET DEFAULT nextval('public.wallets_id_seq'::regclass);


--
-- TOC entry 3370 (class 0 OID 16541)
-- Dependencies: 210
-- Data for Name: goose_db_version; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.goose_db_version (id, version_id, is_applied, tstamp) VALUES (1, 0, true, '2026-07-26 07:19:52.520499') ON CONFLICT DO NOTHING;
INSERT INTO public.goose_db_version (id, version_id, is_applied, tstamp) VALUES (2, 20260725063259, true, '2026-07-26 07:19:52.529168') ON CONFLICT DO NOTHING;


--
-- TOC entry 3378 (class 0 OID 16593)
-- Dependencies: 218
-- Data for Name: transaction_ledgers; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.transaction_ledgers (id, created_at, updated_at, transaction_id, wallet_id, ledger, reference, amount) VALUES (1, '2026-07-26 07:20:09.182536', '2026-07-26 07:20:09.182536', 1, 1, 'CREDIT', 'TOP_UP', 10000) ON CONFLICT DO NOTHING;
INSERT INTO public.transaction_ledgers (id, created_at, updated_at, transaction_id, wallet_id, ledger, reference, amount) VALUES (2, '2026-07-26 07:20:09.182536', '2026-07-26 07:20:09.182536', 2, 2, 'CREDIT', 'TOP_UP', 5000) ON CONFLICT DO NOTHING;
INSERT INTO public.transaction_ledgers (id, created_at, updated_at, transaction_id, wallet_id, ledger, reference, amount) VALUES (3, '2026-07-26 07:20:09.182536', '2026-07-26 07:20:09.182536', 3, 3, 'CREDIT', 'TOP_UP', 2500) ON CONFLICT DO NOTHING;


--
-- TOC entry 3376 (class 0 OID 16580)
-- Dependencies: 216
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.transactions (id, created_at, updated_at, transaction_id, status) VALUES (1, '2026-07-26 07:20:09.17417', '2026-07-26 07:20:09.17417', 'TOPUP-WALLET-1', 'SUCCESS') ON CONFLICT DO NOTHING;
INSERT INTO public.transactions (id, created_at, updated_at, transaction_id, status) VALUES (2, '2026-07-26 07:20:09.17417', '2026-07-26 07:20:09.17417', 'TOPUP-WALLET-2', 'SUCCESS') ON CONFLICT DO NOTHING;
INSERT INTO public.transactions (id, created_at, updated_at, transaction_id, status) VALUES (3, '2026-07-26 07:20:09.17417', '2026-07-26 07:20:09.17417', 'TOPUP-WALLET-3', 'SUCCESS') ON CONFLICT DO NOTHING;


--
-- TOC entry 3372 (class 0 OID 16548)
-- Dependencies: 212
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.users (id, created_at, updated_at, deleted_at, full_name, email, password) VALUES (1, '2026-07-26 07:20:09.142173', '2026-07-26 07:20:09.142173', NULL, 'Justin Bieber', 'justin@example.com', 'password') ON CONFLICT DO NOTHING;
INSERT INTO public.users (id, created_at, updated_at, deleted_at, full_name, email, password) VALUES (2, '2026-07-26 07:20:09.142173', '2026-07-26 07:20:09.142173', NULL, 'Taylor Swift', 'taylor@example.com', 'password') ON CONFLICT DO NOTHING;
INSERT INTO public.users (id, created_at, updated_at, deleted_at, full_name, email, password) VALUES (3, '2026-07-26 07:20:09.142173', '2026-07-26 07:20:09.142173', NULL, 'Ed Sheeran', 'ed@example.com', 'password') ON CONFLICT DO NOTHING;


--
-- TOC entry 3374 (class 0 OID 16561)
-- Dependencies: 214
-- Data for Name: wallets; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.wallets (id, created_at, updated_at, deleted_at, user_id, balance) VALUES (1, '2026-07-26 07:20:09.161862', '2026-07-26 07:20:09.161862', NULL, 1, 10000) ON CONFLICT DO NOTHING;
INSERT INTO public.wallets (id, created_at, updated_at, deleted_at, user_id, balance) VALUES (2, '2026-07-26 07:20:09.161862', '2026-07-26 07:20:09.161862', NULL, 2, 5000) ON CONFLICT DO NOTHING;
INSERT INTO public.wallets (id, created_at, updated_at, deleted_at, user_id, balance) VALUES (3, '2026-07-26 07:20:09.161862', '2026-07-26 07:20:09.161862', NULL, 3, 2500) ON CONFLICT DO NOTHING;


--
-- TOC entry 3390 (class 0 OID 0)
-- Dependencies: 209
-- Name: goose_db_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.goose_db_version_id_seq', 2, true);


--
-- TOC entry 3391 (class 0 OID 0)
-- Dependencies: 217
-- Name: transaction_ledgers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.transaction_ledgers_id_seq', 3, true);


--
-- TOC entry 3392 (class 0 OID 0)
-- Dependencies: 215
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.transactions_id_seq', 3, true);


--
-- TOC entry 3393 (class 0 OID 0)
-- Dependencies: 211
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- TOC entry 3394 (class 0 OID 0)
-- Dependencies: 213
-- Name: wallets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.wallets_id_seq', 3, true);


--
-- TOC entry 3206 (class 2606 OID 16546)
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- TOC entry 3223 (class 2606 OID 16603)
-- Name: transaction_ledgers transaction_ledgers_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transaction_ledgers
    ADD CONSTRAINT transaction_ledgers_pkey PRIMARY KEY (id);


--
-- TOC entry 3218 (class 2606 OID 16588)
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 3221 (class 2606 OID 16590)
-- Name: transactions transactions_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_transaction_id_key UNIQUE (transaction_id);


--
-- TOC entry 3210 (class 2606 OID 16557)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3213 (class 2606 OID 16569)
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (id);


--
-- TOC entry 3215 (class 2606 OID 16571)
-- Name: wallets wallets_user_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_user_id_key UNIQUE (user_id);


--
-- TOC entry 3224 (class 1259 OID 16616)
-- Name: transaction_ledgers_reference_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX transaction_ledgers_reference_idx ON public.transaction_ledgers USING btree (reference);


--
-- TOC entry 3225 (class 1259 OID 16614)
-- Name: transaction_ledgers_transaction_id_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX transaction_ledgers_transaction_id_idx ON public.transaction_ledgers USING btree (transaction_id);


--
-- TOC entry 3226 (class 1259 OID 16615)
-- Name: transaction_ledgers_wallet_id_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX transaction_ledgers_wallet_id_idx ON public.transaction_ledgers USING btree (wallet_id);


--
-- TOC entry 3219 (class 1259 OID 16591)
-- Name: transactions_status_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX transactions_status_idx ON public.transactions USING btree (status);


--
-- TOC entry 3207 (class 1259 OID 16559)
-- Name: users_deleted_at_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX users_deleted_at_idx ON public.users USING btree (deleted_at);


--
-- TOC entry 3208 (class 1259 OID 16558)
-- Name: users_email_unique_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX users_email_unique_idx ON public.users USING btree (email) WHERE (deleted_at IS NULL);


--
-- TOC entry 3211 (class 1259 OID 16578)
-- Name: wallets_deleted_at_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX wallets_deleted_at_idx ON public.wallets USING btree (deleted_at);


--
-- TOC entry 3216 (class 1259 OID 16577)
-- Name: wallets_user_id_unique_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX wallets_user_id_unique_idx ON public.wallets USING btree (user_id) WHERE (deleted_at IS NULL);


--
-- TOC entry 3228 (class 2606 OID 16604)
-- Name: transaction_ledgers transaction_ledgers_transaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transaction_ledgers
    ADD CONSTRAINT transaction_ledgers_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id);


--
-- TOC entry 3229 (class 2606 OID 16609)
-- Name: transaction_ledgers transaction_ledgers_wallet_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transaction_ledgers
    ADD CONSTRAINT transaction_ledgers_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.wallets(id);


--
-- TOC entry 3227 (class 2606 OID 16572)
-- Name: wallets wallets_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2026-07-26 07:22:38 UTC

--
-- PostgreSQL database dump complete
--

\unrestrict lmb2SFOZjv7JHAsg1uhif8va9KnhBxO8FfyAwGgBMlQM8u6N3FBfRGEDmfcyAE2

